# Generated by Django 4.2.3 on 2023-07-28 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('djangoDelight', '0001_initial'), ('djangoDelight', '0002_ingredient_unit_alter_menuitem_price_and_more'), ('djangoDelight', '0003_menuitem_cost_alter_ingredient_unit_and_more'), ('djangoDelight', '0004_alter_purchase_menuitem'), ('djangoDelight', '0005_alter_purchase_menuitem'), ('djangoDelight', '0006_alter_purchase_menuitem'), ('djangoDelight', '0007_alter_purchase_menuitem'), ('djangoDelight', '0008_remove_purchase_datetime_purchase_date'), ('djangoDelight', '0009_alter_purchase_date_alter_purchase_menuitem'), ('djangoDelight', '0010_alter_purchase_date'), ('djangoDelight', '0011_alter_purchase_menuitem')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('unit', models.CharField(choices=[('cup', 'Cup'), ('ea', '#'), ('g', 'grams'), ('ml', 'mL')], default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoDelight.ingredient')),
                ('menuitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoDelight.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('menuitem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='djangoDelight.menuitem')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
